// Extracts components.schemas from apps/api/openapi/openapi.yaml as plain
// JSON (src/schemas.json), run as part of `npm run generate` alongside
// openapi-typescript's src/openapi.d.ts. Both outputs trace back to the
// exact same YAML source in the same generation step, so the static
// TypeScript types and the runtime Ajv validators built from schemas.json
// cannot drift from each other by construction — see design.md's
// Decision 2 in openspec/changes/strengthen-contracts-typing.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

import { load } from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const openapiPath = resolve(__dirname, "../../../apps/api/openapi/openapi.yaml");
const schemasOutputPath = resolve(__dirname, "../src/schemas.json");
const typesOutputPath = resolve(__dirname, "../src/openapi-schemas.ts");

const document = load(readFileSync(openapiPath, "utf8"));
const schemas = document?.components?.schemas;

if (!schemas || typeof schemas !== "object") {
  throw new Error(`No components.schemas found in ${openapiPath}`);
}

writeFileSync(schemasOutputPath, `${JSON.stringify(schemas, null, 2)}\n`);

// Every OpenAPI schema, re-exported under its own name from the generated
// components["schemas"][...] path — auto-generated, never hand-edited (see
// this file's own header and index.ts). A schema name that isn't a valid
// TS identifier would need quoting here; none of this repo's schema names
// need that today.
const names = Object.keys(schemas).sort((a, b) => a.localeCompare(b));
const header = [
  "// AUTO-GENERATED by scripts/extract-schemas.mjs — do not hand-edit.",
  "// Regenerate via `npm run generate` when apps/api/openapi/openapi.yaml changes.",
  'import type { components } from "./openapi.js";',
  "",
].join("\n");
const body = names
  .map((name) => `export type ${name} = components["schemas"]["${name}"];`)
  .join("\n");

writeFileSync(typesOutputPath, `${header}${body}\n`);

console.log(`Wrote ${names.length} schemas to ${schemasOutputPath} and ${typesOutputPath}`);
